DELETE http://localhost:8080/events/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3R1c2VyMkB0ZXN0aW5nLmNvbSIsImV4cCI6MTcwNjQ3NzA3NiwidXNlcklkIjoyfQ.n62Mbw-IFEScah8JU6ATSkwpYbWFSfJO3EpFTfLpuUY