PUT http://localhost:8080/events/1
content-type: application/json

{
  "name": "Updated Test event",
  "description": "Updated test event",
  "location": "Updated test location",
  "dateTime": "2025-01-01T15:30:00.000Z"
}